### ISSUE TITLE
Calculations on Whatsapp System Design - Storage

### ISSUE THREAD

**Issue by amandavarella** [karanpratapsingh/system-design#20]
On the Whatsapp system design, you have the following paragraph:

>As per our requirements, we also know that around 5 percent of our daily messages (100 million) are media files. If we assume each file is 50 KB on average, we will require 10 TB of storage every day.

When you make the calculation, you show the math as:

`100 million * 100 KB`

when I was expecting

`100 million * 50 KB`, given that you said that each file is 50 KB on average

leading to 5 TB of storage instead of the 10 TB you've arrived. What am I missing?

**Comment by karanpratapsingh** [comment]
Hi @amandavarella, you're right, that's a typo. I'll fix it soon. Thanks

**Comment by karanpratapsingh** [comment]
Fixed in https://github.com/karanpratapsingh/system-design/commit/20ea643af4bde5d3d911a0b20bce80a7c7b9df2c
