### ISSUE TITLE
Breakup into folders etc

### ISSUE THREAD

**Issue by gedw99** [karanpratapsingh/system-design#21]
Very impressive content . I did not know there was a 3 phase commit ;) 

wondering if the markdown could be in many folded to make it easier to read.

My use case is when I need to send a link to someone to get them up to speed on a concept. I know the anchors work fine with everything in the current massive readme.md but it’s a bit overwhelming.

the other reason is load time

**Comment by karanpratapsingh** [comment]
Hi @gedw99, Thank you, I'm glad it was helpful. I agree, but this markdown is auto-generated from my [course on my website](https://www.karanpratapsingh.com/courses/system-design where each topic is broken into sections and easy to navigate. You can also get a copy of the pdf book from [leanpub](https://leanpub.com/systemdesign). I hope this helps.
