### ISSUE TITLE
Epub file is larger than 50mb which is not allow by the Send to Kindle desktop application

### ISSUE THREAD

**Issue by kdawgwilk** [karanpratapsingh/system-design#26]
**Is your feature request related to a problem? Please describe.**

Unable to send the epub file to my kindle

**Describe the solution you'd like**

Optimize some of the assets to put the file size under 50mb

**Additional context**

<img width="553" alt="image" src="https://github.com/karanpratapsingh/system-design/assets/7799267/89d17955-ce3c-4d7d-a011-85a7843623ed">

**Comment by dhechye** [comment]
Turun faile

**Comment by dhechye** [comment]
https://github.com/karanpratapsingh/system-design/issues/26#issue-1792379582

**Comment by kdawgwilk** [comment]
I don't think this has been resolved?
