### ISSUE TITLE
GitHub markdown rendering issue in URL Shortener -> High-level design -> URL Encoding section

### ISSUE THREAD

**Issue by pingssgp** [karanpratapsingh/system-design#3]
# Description  

There is an issue with GitHub rendering the content in a `\begin{gather*}` to `\end{gather*}` section. 

# Browser & platform

Browser: Safari Version 15.5 (17613.2.7.1.8), Chrome Version 104.0.5112.101 (Official Build) (x86_64)  
OS: macOS Monterey Version 12.4 (21F79)  

# Steps to reproduce, current behaviour

1. Open the `README.md` file at the top level.
2. Scroll down to the section at `URL Shortener -> High-level design -> URL Encoding`.
3. Look at how GitHub renders the following section

<img width="805" alt="image" src="https://user-images.githubusercontent.com/7234966/185117127-972eff91-b978-4292-962a-815f01c75cc9.png">

# Expected behaviour

The GitHub renderer should display the content as it is rendered in VSCode, as in the screenshot below. 

<img width="828" alt="image" src="https://user-images.githubusercontent.com/7234966/185117951-4ca80330-a783-4447-8826-80c0af835f89.png">

# Notes

No changes were made to `README.md` to render it on VSCode.

**Comment by karanpratapsingh** [comment]
Thanks for the details, I really appreciate it. Fixed in commit a7983b2520c5f02b5fee8facc13d422b5cda5ec5
