### ISSUE TITLE
Mistake in the Sparse Indexing section

### ISSUE THREAD

**Issue by aniketsingh98571** [karanpratapsingh/system-design#36]
**Is your feature request related to a problem? Please describe.**
There is a small mistake in the Sparse Indexing Sectionm,where instead of "records", "index" should be written

![image](https://github.com/karanpratapsingh/system-design/assets/63097956/8a42a0ad-5d15-42be-b794-a539072fa911)
Please see above image for reference @karanpratapsingh 
**Describe the solution you'd like**

**Additional context**

**Comment by karanpratapsingh** [comment]
Fixed
