### ISSUE TITLE
Make fornt in images more readable

### ISSUE THREAD

**Issue by BanzaiTokyo** [karanpratapsingh/system-design#4]
First of all, great job! 
One suggestion I would like to make is to make the font that you use in the images more readable - e.g. make it larger or find another font face.
It would make it easier to read the document directly from the github website.

![image](https://user-images.githubusercontent.com/2467506/185434741-f0586821-d320-44e2-b315-81d5bad9d935.png)

**Comment by hamirmahal** [comment]
Hmm... how is this? It changes the font from "hand-drawn" to "normal".

It also updates the font size to medium.

Anyone wanting to update these files can do so by importing the `.excalidraw` files from this repository to https://excalidraw.com/, as mentioned in one of the `README.md`s in this repository.

![image](https://user-images.githubusercontent.com/43425812/185538254-e35d26ac-324c-4ea5-afa0-385c00bb2d22.png)

**Comment by hamirmahal** [comment]
Hmm... how is this? It changes the font from "hand-drawn" to "normal".

<details>
<summary>Updated image</summary>

![image](https://user-images.githubusercontent.com/43425812/185538254-e35d26ac-324c-4ea5-afa0-385c00bb2d22.png)
</details>

It also updates the font size to medium.

Anyone wanting to update these files can do so by importing the `.excalidraw` files from this repository to https://excalidraw.com/, as mentioned in one of the `README.md`s in this repository.

**Comment by KetanParmar07** [comment]
Hello, sir I am interested in solving this issue. so please assign to me this issue.

**Comment by KetanParmar07** [comment]
please, assign to me this issue.

**Comment by KetanParmar07** [comment]
what should i do??
and in which file to add solution??
please let me know.

**Comment by karanpratapsingh** [comment]
Thank you @BanzaiTokyo for the feedback, I agree with @hamirmahal. 
Feel free to import the `*.excalidraw` file and change it to your preference locally.

**Comment by karanpratapsingh** [comment]
I'm closing this issue for now
