### ISSUE TITLE
Records and fields vs rows and columns in general DBMS discussions

### ISSUE THREAD

**Issue by antichris** [karanpratapsingh/system-design#7]
The terms "row" and "column" are specific to table-based, relational ("SQL") DBMS. In the sections where DBMS are discussed in general terms, e.g. comparing SQL vs NoSQL systems, using the terms "record" and "field" would be more inclusive. Especially so when referring to records in NoSQL, like in this paragraph:

> Whereas in NoSQL, schemas are dynamic. Columns can be added on the fly, and each row (or equivalent) doesn't have to contain data for each column.

Instead, it could read

> Whereas in NoSQL, schemas are dynamic. Fields can be added on the fly, and each record doesn't have to contain data for each field.

It could be argued that the terms "record" and "field" apply more loosely in the graph storage context, although a node can be thought of (and often is implemented) as a record, holding "fields" of property or edge meta types.

Key-value stores don't even have the concept of field ("column") at all, since all records are just that — records.

In the end, regardless of the underlying model, all DBMS hold records that tie together one or more closely related pieces of data — fields. Only information laid out in a table layout can have "rows" and "columns".

**Comment by karanpratapsingh** [comment]
This is a valid point, thank you @antichris I've made the changes [here](https://github.com/karanpratapsingh/system-design/pull/10/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1223) https://github.com/karanpratapsingh/system-design/pull/10
